version: "3.8"

services:
  api-solid-db:
    image: bitnami/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    volumes:
      - ./db-volume:/bitnami/postgresql
    networks:
      - compose-shared-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - api-solid-db
    networks:
      - compose-shared-network
  api-solid-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env.compose
    ports:
      - 3000:3000
      - 9221:9221
    depends_on:
      - api-solid-db
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    networks:
      - compose-shared-network
    command: "npm run compose:debug"

networks:
  compose-shared-network:
